version: '3.7'

services:

  gateway:
    container_name: gateway
    image: gatewaytutorial/gateway
    build:
      context: GatewayApi
    ports:
      - 7000:80

  catalogapi:
    container_name: catalogapi
    image: gatewaytutorial/catalog
    build:
      context: CatalogApi
    ports:
      - 7001:80

  ordersapi:
    container_name: ordersapi
    image: gatewaytutorial/orders
    build:
      context: OrdersApi
    ports:
      - 7002:80